//
//  TestShowModels.swift
//  TestMyLib
//
//  Created by msm72 on 4/30/19.
//  Copyright (c) 2019 golos.io. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CyberSwift

// MARK: - Data models
enum TestShowModels {
    // MARK: - Use cases
    enum Something {
        struct RequestModel {
        }
        
        struct ResponseModel {
        }
        
        struct ViewModel {
        }
    }
}
