//
//  TestShowInteractor.swift
//  TestMyLib
//
//  Created by msm72 on 4/30/19.
//  Copyright (c) 2019 golos.io. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CyberSwift

// MARK: - Business Logic protocols
protocol TestShowBusinessLogic {
    func doSomething(withRequestModel requestModel: TestShowModels.Something.RequestModel)
}

protocol TestShowDataStore {
//     var name: String { get set }
}

class TestShowInteractor: TestShowBusinessLogic, TestShowDataStore {
    // MARK: - Properties
    var presenter: TestShowPresentationLogic?
    var worker: TestShowWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: TestShowModels.Something.RequestModel) {
        worker = TestShowWorker()
        worker?.doSomeWork()
        
        let responseModel = TestShowModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
