//
//  TestShowViewController.swift
//  TestMyLib
//
//  Created by msm72 on 4/30/19.
//  Copyright (c) 2019 golos.io. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CyberSwift

// MARK: - Input & Output protocols
protocol TestShowDisplayLogic: class {
    func displaySomething(fromViewModel viewModel: TestShowModels.Something.ViewModel)
}

class TestShowViewController: UIViewController {
    // MARK: - Properties
    var interactor: TestShowBusinessLogic?
    var router: (NSObjectProtocol & TestShowRoutingLogic & TestShowDataPassing)?
    
    
    // MARK: - IBOutlets
    
    
    // MARK: - Class Initialization
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
        setup()
    }

    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    
    
    // MARK: - Setup
    private func setup() {
        let viewController          =   self
        let interactor              =   TestShowInteractor()
        let presenter               =   TestShowPresenter()
        let router                  =   TestShowRouter()
        
        viewController.interactor   =   interactor
        viewController.router       =   router
        interactor.presenter        =   presenter
        presenter.viewController    =   viewController
        router.viewController       =   viewController
        router.dataStore            =   interactor
    }
    
    
    // MARK: - Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    
    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.loadViewSettings()
    }
    
    
    // MARK: - Custom Functions
    private func loadViewSettings() {
        let requestModel = TestShowModels.Something.RequestModel()
        interactor?.doSomething(withRequestModel: requestModel)
    }
}


// MARK: - TestShowDisplayLogic
extension TestShowViewController: TestShowDisplayLogic {
    func displaySomething(fromViewModel viewModel: TestShowModels.Something.ViewModel) {
        // NOTE: Display the result from the Presenter

    }
}
