//
//  TestShowPresenter.swift
//  TestMyLib
//
//  Created by msm72 on 4/30/19.
//  Copyright (c) 2019 golos.io. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CyberSwift

// MARK: - Presentation Logic protocols
protocol TestShowPresentationLogic {
    func presentSomething(fromResponseModel responseModel: TestShowModels.Something.ResponseModel)
}

class TestShowPresenter: TestShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: TestShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentSomething(fromResponseModel responseModel: TestShowModels.Something.ResponseModel) {
        let viewModel = TestShowModels.Something.ViewModel()
        viewController?.displaySomething(fromViewModel: viewModel)
    }
}
