//
//  TestShowRouter.swift
//  TestMyLib
//
//  Created by msm72 on 4/30/19.
//  Copyright (c) 2019 golos.io. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CyberSwift

// MARK: - Input & Output protocols
@objc protocol TestShowRoutingLogic {
//    func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol TestShowDataPassing {
    var dataStore: TestShowDataStore? { get }
}

class TestShowRouter: NSObject, TestShowRoutingLogic, TestShowDataPassing {
    // MARK: - Properties
    weak var viewController: TestShowViewController?
    var dataStore: TestShowDataStore?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .severe)
    }
    

    // MARK: - Routing
//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
//    }
    
    
    // MARK: - Navigation
//    func navigateToSomewhere(source: TestShowViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
    
    
    // MARK: - Passing data
//    func passDataToSomewhere(source: TestShowDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
